# Generated by Django 4.0.10 on 2023-07-21 10:44

from django.db import migrations, models
import yoolink.ycms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0003_alter_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code',
            field=models.JSONField(default=yoolink.ycms.models.default_code),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(default='This Blog is empty'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(blank=True, default='', upload_to=yoolink.ycms.models.upload_to_blog_image),
        ),
    ]
