# Generated by Django 4.0.10 on 2023-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0005_blog_active_fileentry_title_galeryimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('header', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
