# Generated by Django 4.0.10 on 2023-08-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0006_textcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='buttonText',
            field=models.CharField(default='', max_length=60),
        ),
    ]
