# Generated by Django 4.0.10 on 2023-08-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0007_textcontent_buttontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='description',
            field=models.CharField(default='', max_length=700),
        ),
    ]
