# Generated by Django 4.0.10 on 2023-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0008_alter_textcontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentry',
            name='place',
            field=models.CharField(default='', max_length=60),
        ),
    ]
