# Generated by Django 4.0.10 on 2023-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0009_fileentry_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='place',
            field=models.CharField(default='', max_length=60, unique=True),
        ),
    ]
