# Generated by Django 4.0.10 on 2023-08-05 15:11

from django.db import migrations, models
import yoolink.ycms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0011_alter_fileentry_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='place',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='galeryimage',
            name='upload',
            field=models.ImageField(upload_to=yoolink.ycms.models.upload_to_galery_image),
        ),
    ]
