# Generated by Django 4.0.10 on 2023-09-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0012_galerie_place_alter_galerie_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
