# Generated by Django 4.0.10 on 2024-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0018_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Offen'), ('SHIPPED', 'Versendet'), ('PAID', 'Bezahlt'), ('COMPLETED', 'Abgeschlossen')], default='OPEN', max_length=20),
        ),
    ]
