# Generated by Django 4.0.10 on 2024-01-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
