# Generated by Django 4.0.10 on 2024-02-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0021_order_buyer_address_order_uuid_order_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Offen'), ('PAID', 'Bezahlt'), ('READY_FOR_PICKUP', 'Bereit zur Abholung'), ('SHIPPED', 'Versendet'), ('COMPLETED', 'Abgeschlossen')], default='OPEN', max_length=20),
        ),
    ]
