# Generated by Django 4.0.10 on 2024-02-06 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ycms', '0022_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ycms.order'),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Montag'), ('TUE', 'Dienstag'), ('WED', 'Mittwoch'), ('THU', 'Donnerstag'), ('FRI', 'Freitag')], max_length=3)),
                ('is_open', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('has_lunch_break', models.BooleanField(default=False)),
                ('lunch_break_start', models.TimeField(blank=True, null=True)),
                ('lunch_break_end', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
