# Generated by Django 4.0.10 on 2024-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0023_remove_order_items_orderitem_order_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('INVOICE', 'Rechnung'), ('PICKUP', 'Zahlung bei Abholung')], default='INVOICE', max_length=20),
        ),
    ]
