# Generated by Django 4.0.10 on 2024-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0024_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='day',
            field=models.CharField(choices=[('MON', 'Montag'), ('TUE', 'Dienstag'), ('WED', 'Mittwoch'), ('THU', 'Donnerstag'), ('FRI', 'Freitag'), ('SAT', 'Samstag')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='end_time',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
