# Generated by Django 4.0.10 on 2024-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0025_alter_openinghours_day_alter_openinghours_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='day',
            field=models.CharField(choices=[('MON', 'Montag'), ('TUE', 'Dienstag'), ('WED', 'Mittwoch'), ('THU', 'Donnerstag'), ('FRI', 'Freitag'), ('SAT', 'Samstag'), ('SUN', 'Sonntag')], max_length=3, unique=True),
        ),
    ]
