# Generated by Django 4.0.10 on 2024-02-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0026_alter_openinghours_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prename', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('SHIPPING', 'Lieferung'), ('PICKUP', 'Abholung')], default='SHIPPING', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ycms.shippingaddress'),
        ),
    ]
