# Generated by Django 4.0.10 on 2024-02-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0027_shippingaddress_remove_order_payment_order_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ycms.shippingaddress'),
        ),
    ]
