# Generated by Django 4.0.10 on 2024-11-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0033_usersettings_global_font_usersettings_vacation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('image', models.CharField(default='', max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('years_with_team', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(default='Mitarbeiter', max_length=100)),
                ('note', models.TextField(default='')),
            ],
        ),
    ]
