# Generated by Django 4.0.10 on 2024-11-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0034_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=3000),
        ),
    ]
