# Generated by Django 4.0.10 on 2025-03-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0035_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
