# Generated by Django 4.0.10 on 2025-03-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0036_faq_answer_de_faq_answer_en_faq_question_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='buttonText_de',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='buttonText_en',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='description_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='header_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='header_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='title_de',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='title_en',
            field=models.CharField(default='', max_length=140, null=True),
        ),
    ]
