# Generated by Django 4.0.10 on 2025-03-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0037_textcontent_buttontext_de_textcontent_buttontext_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentry',
            name='title_de',
            field=models.CharField(default='Bildtitel', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fileentry',
            name='title_en',
            field=models.CharField(default='Bildtitel', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galerie',
            name='description_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='galerie',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='galerie',
            name='title_de',
            field=models.CharField(default='Titel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galerie',
            name='title_en',
            field=models.CharField(default='Titel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galeryimage',
            name='title_de',
            field=models.CharField(default='Bildtitel', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galeryimage',
            name='title_en',
            field=models.CharField(default='Bildtitel', max_length=200, null=True),
        ),
    ]
