# Generated by Django 4.0.10 on 2025-04-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0038_fileentry_title_de_fileentry_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Button-Text')),
                ('url', models.URLField(max_length=500, verbose_name='Ziel-URL')),
                ('hover_text', models.CharField(blank=True, help_text='Optionaler Text, der beim Hover angezeigt wird', max_length=200, verbose_name='Tooltip (Hover-Text)')),
                ('target', models.CharField(choices=[('_self', 'Gleiches Fenster (_self)'), ('_blank', 'Neuer Tab (_blank)'), ('_parent', 'Elternelement (_parent)'), ('_top', 'Oberstes Fenster (_top)')], default='_self', max_length=20, verbose_name='Link-Ziel (_blank etc.)')),
                ('css_classes', models.CharField(blank=True, help_text='Optional: Zusätzliche Tailwind oder CSS-Klassen', max_length=300, verbose_name='CSS-Klassen')),
                ('icon', models.CharField(blank=True, help_text='z.B. Heroicon oder FontAwesome Klassenname', max_length=100, verbose_name='Icon (optional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('monthly_price', models.CharField(help_text="z.B. '25 €' oder '? €'", max_length=20, verbose_name='Monatlicher Preis')),
                ('one_time_price', models.CharField(help_text="z.B. '250 €' oder '? €'", max_length=50, verbose_name='Einmalzahlung')),
                ('description', models.TextField(blank=True, help_text='Kleiner Infotext unter dem Button', verbose_name='Beschreibung')),
                ('order', models.PositiveIntegerField(default=0, help_text='Reihenfolge der Karte auf der Seite', verbose_name='Reihenfolge')),
                ('animation', models.CharField(choices=[('fade-right', 'Fade Right'), ('fade-left', 'Fade Left'), ('zoom-in', 'Zoom In'), ('fade-up', 'Fade Up')], default='fade-up', max_length=50, verbose_name='AOS-Animation')),
                ('animation_delay', models.PositiveIntegerField(default=100, verbose_name='Animationsverzögerung (ms)')),
                ('button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ycms.button', verbose_name='Zugehöriger Button')),
            ],
            options={
                'verbose_name': 'Pricing-Karte',
                'verbose_name_plural': 'Pricing-Karten',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Featuretext')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('pricing_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ycms.pricingcard')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
    ]
