# Generated by Django 4.0.10 on 2025-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0039_button_pricingcard_pricingfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingcard',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
