# Generated by Django 4.0.10 on 2025-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0040_pricingcard_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='hover_text_de',
            field=models.CharField(blank=True, help_text='Optionaler Text, der beim Hover angezeigt wird', max_length=200, null=True, verbose_name='Tooltip (Hover-Text)'),
        ),
        migrations.AddField(
            model_name='button',
            name='hover_text_en',
            field=models.CharField(blank=True, help_text='Optionaler Text, der beim Hover angezeigt wird', max_length=200, null=True, verbose_name='Tooltip (Hover-Text)'),
        ),
        migrations.AddField(
            model_name='button',
            name='text_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Button-Text'),
        ),
        migrations.AddField(
            model_name='button',
            name='text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Button-Text'),
        ),
        migrations.AddField(
            model_name='pricingcard',
            name='description_de',
            field=models.TextField(blank=True, help_text='Kleiner Infotext unter dem Button', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='pricingcard',
            name='description_en',
            field=models.TextField(blank=True, help_text='Kleiner Infotext unter dem Button', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='pricingcard',
            name='monthly_price_de',
            field=models.CharField(help_text="z.B. '25 €' oder '? €'", max_length=20, null=True, verbose_name='Monatlicher Preis'),
        ),
        migrations.AddField(
            model_name='pricingcard',
            name='monthly_price_en',
            field=models.CharField(help_text="z.B. '25 €' oder '? €'", max_length=20, null=True, verbose_name='Monatlicher Preis'),
        ),
        migrations.AddField(
            model_name='pricingcard',
            name='one_time_price_de',
            field=models.CharField(help_text="z.B. '250 €' oder '? €'", max_length=50, null=True, verbose_name='Einmalzahlung'),
        ),
        migrations.AddField(
            model_name='pricingcard',
            name='one_time_price_en',
            field=models.CharField(help_text="z.B. '250 €' oder '? €'", max_length=50, null=True, verbose_name='Einmalzahlung'),
        ),
        migrations.AddField(
            model_name='pricingcard',
            name='title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='pricingcard',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='pricingfeature',
            name='text_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Featuretext'),
        ),
        migrations.AddField(
            model_name='pricingfeature',
            name='text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Featuretext'),
        ),
    ]
