# Generated by Django 4.0.10 on 2025-05-04 08:52

from django.db import migrations, models
import yoolink.ycms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0042_remove_pricingcard_monthly_price_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=yoolink.ycms.models.unique_anyfile_name, validators=[yoolink.ycms.models.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='Dateititel', max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
