# Generated by Django 4.0.10 on 2025-05-16 15:35

from django.db import migrations, models
import yoolink.ycms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0044_usersettings_favicon_usersettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Video-Datei (.mp4, .mov, .webm)', upload_to=yoolink.ycms.models.unique_video_name, validators=[yoolink.ycms.models.validate_video_extension])),
                ('thumbnail', models.ImageField(blank=True, help_text='Poster-Thumbnail für Video', null=True, upload_to='yoolink/thumbnails/', validators=[yoolink.ycms.models.validate_image_extension])),
                ('subtitle_file', models.FileField(blank=True, help_text='Optional: Untertitel im .vtt Format', null=True, upload_to='yoolink/subtitles/', validators=[yoolink.ycms.models.validate_vtt_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, help_text='Titel für das Video', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Beschreibung / Caption des Videos')),
                ('duration', models.DurationField(blank=True, help_text='Laufzeit des Videos (z.\u202fB. für SEO oder schema.org)', null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alt-Text für SEO & Barrierefreiheit', max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Kommaseparierte Tags (optional)', max_length=255)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
