# Generated by Django 4.0.10 on 2025-06-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0045_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='duration',
            field=models.DurationField(blank=True, help_text='Laufzeit des Videos (z.B. für SEO oder schema.org)', null=True),
        ),
    ]
