# Generated by Django 4.0.10 on 2025-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0046_alter_videofile_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anyfile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
