# Generated by Django 4.0.10 on 2025-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0047_alter_anyfile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='place',
            field=models.CharField(default='', max_length=60),
        ),
    ]
