# Generated by Django 4.0.10 on 2025-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0048_videofile_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='autoplay',
            field=models.BooleanField(default=False, help_text='Video automatisch abspielen?'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='loop',
            field=models.BooleanField(default=False, help_text='Video in Endlosschleife?'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='muted',
            field=models.BooleanField(default=False, help_text='Video stumm starten?'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='playsinline',
            field=models.BooleanField(default=True, help_text='Video inline abspielen (bes. für iOS)?'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='preload',
            field=models.CharField(choices=[('auto', 'Auto'), ('metadata', 'Nur Metadaten'), ('none', 'Nichts')], default='metadata', help_text='Preload-Verhalten beim Seitenladen', max_length=20),
        ),
        migrations.AddField(
            model_name='videofile',
            name='show_controls',
            field=models.BooleanField(default=True, help_text='Standard Video Controls anzeigen?'),
        ),
    ]
