# Generated by Django 4.0.10 on 2025-09-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0049_videofile_autoplay_videofile_loop_videofile_muted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('fr', 'Französisch')], default='de', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='original',
            field=models.ForeignKey(blank=True, help_text='Bezieht sich auf den Original-Blog (z.B. auf Deutsch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='ycms.blog'),
        ),
    ]
