# Generated by Django 4.0.10 on 2025-10-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0050_blog_language_blog_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='anyfile',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anyfile',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anyfile',
            name='title_de',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anyfile',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='alt_text_de',
            field=models.CharField(blank=True, help_text='Alt-Text für SEO & Barrierefreiheit', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Alt-Text für SEO & Barrierefreiheit', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='description_de',
            field=models.TextField(blank=True, help_text='Beschreibung / Caption des Videos', null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='description_en',
            field=models.TextField(blank=True, help_text='Beschreibung / Caption des Videos', null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='place_de',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='place_en',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='tags_de',
            field=models.CharField(blank=True, help_text='Kommaseparierte Tags (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='tags_en',
            field=models.CharField(blank=True, help_text='Kommaseparierte Tags (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='title_de',
            field=models.CharField(blank=True, help_text='Titel für das Video', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='title_en',
            field=models.CharField(blank=True, help_text='Titel für das Video', max_length=255, null=True),
        ),
    ]
