# Generated by Django 4.0.10 on 2025-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0053_notification_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='vacation_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='vacation_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
