# Generated by Django 4.0.10 on 2025-10-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0054_usersettings_vacation_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='vacationText_de',
            field=models.CharField(default='Wir sind aktuell im Urlaub. Ab dem XX.XX sind wir wieder für Sie da!', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='vacationText_en',
            field=models.CharField(default='Wir sind aktuell im Urlaub. Ab dem XX.XX sind wir wieder für Sie da!', max_length=200, null=True),
        ),
    ]
