# Generated by Django 4.0.10 on 2025-11-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0055_usersettings_vacationtext_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_spam'], name='ycms_notifi_is_spam_198dcc_idx'),
        ),
    ]
