# Generated by Django 4.0.10 on 2025-12-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0056_notification_is_spam_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
