# Generated by Django 4.0.10 on 2026-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0058_remove_order_buyer_address_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_email_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_email_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.CheckConstraint(condition=models.Q(('two_factor_email_enabled', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='two_factor_requires_email'),
        ),
    ]
