# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0060_privacypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='vacationText',
            field=models.TextField(default='Wir sind aktuell im Urlaub. Ab dem XX.XX sind wir wieder für Sie da!'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='vacationText_de',
            field=models.TextField(default='Wir sind aktuell im Urlaub. Ab dem XX.XX sind wir wieder für Sie da!', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='vacationText_en',
            field=models.TextField(default='Wir sind aktuell im Urlaub. Ab dem XX.XX sind wir wieder für Sie da!', null=True),
        ),
    ]
