# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0061_alter_usersettings_vacationtext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("prefix", models.CharField(editable=False, max_length=32, unique=True)),
                ("key_hash", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[("read", "Nur lesen"), ("write", "Lesen und schreiben")],
                        default="read",
                        max_length=10,
                    ),
                ),
                ("allowed_apps", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Developer API Key",
                "verbose_name_plural": "Developer API Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
