# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0062_developerapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="markdown",
            field=models.TextField(blank=True, default=""),
        ),
    ]
