# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0063_blog_markdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperApiConnectAuthorization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_name", models.CharField(max_length=160)),
                ("redirect_uri", models.URLField(max_length=2048)),
                ("state", models.CharField(blank=True, max_length=500)),
                ("code_challenge", models.CharField(max_length=128)),
                (
                    "code_challenge_method",
                    models.CharField(
                        choices=[("S256", "S256")],
                        default="S256",
                        max_length=12,
                    ),
                ),
                ("code_hash", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[("read", "Nur lesen"), ("write", "Lesen und schreiben")],
                        default="read",
                        max_length=10,
                    ),
                ),
                ("allowed_apps", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_api_connect_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Developer API Connect Authorization",
                "verbose_name_plural": "Developer API Connect Authorizations",
                "ordering": ["-created_at"],
            },
        ),
    ]
