# Generated by Django 5.2.13 on 2026-06-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0069_websitesettings_roles_openinghours"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="owner_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
