# Generated by Django 5.2.13 on 2026-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0070_websitesettings_owner_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileentry",
            name="title",
            field=models.CharField(default="Bildtitel", max_length=1000),
        ),
        migrations.AlterField(
            model_name="fileentry",
            name="title_de",
            field=models.CharField(default="Bildtitel", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="fileentry",
            name="title_en",
            field=models.CharField(default="Bildtitel", max_length=1000, null=True),
        ),
    ]
