# Generated by Django 5.2.13 on 2026-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0071_alter_fileentry_title_alter_fileentry_title_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileentry",
            name="title",
            field=models.TextField(default="Bildtitel"),
        ),
        migrations.AlterField(
            model_name="fileentry",
            name="title_de",
            field=models.TextField(default="Bildtitel", null=True),
        ),
        migrations.AlterField(
            model_name="fileentry",
            name="title_en",
            field=models.TextField(default="Bildtitel", null=True),
        ),
    ]
