# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0072_alter_fileentry_title_alter_fileentry_title_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="title_image_alt",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_image_caption",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_image_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
