# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0073_blog_title_image_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="site_meta_author",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_meta_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
