# Generated by Django 5.2.13 on 2026-06-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0074_websitesettings_site_meta_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Anzeigename in der Auswahl, z.B. 'Startseite – Preise'",
                        max_length=120,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Pfad der Seite, z.B. '/' oder '/kontakt/'",
                        max_length=300,
                        verbose_name="Seitenpfad",
                    ),
                ),
                (
                    "anchor",
                    models.CharField(
                        blank=True,
                        help_text="Abschnitt auf der Seite ohne '#', z.B. 'preise'",
                        max_length=100,
                        verbose_name="Anker (optional)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
            ],
            options={
                "verbose_name": "Seiten-Link",
                "verbose_name_plural": "Seiten-Links",
                "ordering": ["order", "title"],
            },
        ),
        migrations.RemoveField(
            model_name="button",
            name="css_classes",
        ),
        migrations.AddField(
            model_name="button",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "Blau"),
                    ("navy", "Dunkelblau"),
                    ("dark", "Schwarz"),
                    ("emerald", "Grün"),
                    ("white", "Weiß"),
                    ("outline", "Umrandet"),
                ],
                default="blue",
                max_length=20,
                verbose_name="Farbe",
            ),
        ),
        migrations.AlterField(
            model_name="button",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Bootstrap-Icon-Klasse, z.B. 'bi bi-arrow-right'",
                max_length=100,
                verbose_name="Icon (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="button",
            name="target",
            field=models.CharField(
                choices=[("_self", "Gleicher Tab"), ("_blank", "Neuer Tab")],
                default="_self",
                max_length=20,
                verbose_name="Link-Ziel",
            ),
        ),
        migrations.AlterField(
            model_name="button",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Beliebiger Link, z.B. https://example.com oder mailto:info@example.com",
                max_length=500,
                verbose_name="Eigene URL",
            ),
        ),
        migrations.AddField(
            model_name="button",
            name="page_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Internes Link-Ziel; hat Vorrang vor der eigenen URL",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buttons",
                to="ycms.pagelink",
                verbose_name="Interne Seite",
            ),
        ),
    ]
