# Generated by Django 5.2.13 on 2026-06-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0076_recoverybackup"),
    ]

    operations = [
        migrations.AddField(
            model_name="button",
            name="place",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Optionaler Slot-Schlüssel, an dem dieser Button auf einer Seite erscheint (z.B. 'main_cmsinfo_hero_cta').",
                max_length=100,
                verbose_name="Platzierung",
            ),
        ),
        migrations.AlterField(
            model_name="button",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "Blau"),
                    ("navy", "Dunkelblau"),
                    ("dark", "Schwarz"),
                    ("emerald", "Grün"),
                    ("white", "Weiß"),
                    ("outline", "Umrandet"),
                    ("link", "Textlink"),
                ],
                default="blue",
                max_length=20,
                verbose_name="Farbe",
            ),
        ),
    ]
