# Generated by Django 5.2.13 on 2026-08-01 15:08

import yoolink.ycms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0079_strip_language_suffix_from_blog_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="area_served",
            field=models.CharField(
                blank=True,
                default="Plattling, Deggendorf, Niederbayern",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="business_description",
            field=models.CharField(
                blank=True, default="Zahnarztpraxis in Plattling", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="geo_latitude",
            field=models.CharField(blank=True, default="48.7785", max_length=20),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="geo_longitude",
            field=models.CharField(blank=True, default="12.8757", max_length=20),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="price_range",
            field=models.CharField(blank=True, default="Auf Anfrage", max_length=50),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="social_instagram",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="social_x",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="subtitle_file",
            field=models.FileField(
                blank=True,
                help_text="Optional: Untertitel im .vtt Format",
                null=True,
                upload_to="holmer/subtitles/",
                validators=[yoolink.ycms.models.validate_vtt_extension],
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Poster-Thumbnail für Video",
                null=True,
                upload_to="holmer/thumbnails/",
                validators=[yoolink.ycms.models.validate_image_extension],
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="area_served",
            field=models.CharField(
                blank=True,
                default="Plattling, Deggendorf, Niederbayern",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="business_description",
            field=models.CharField(
                blank=True, default="Zahnarztpraxis in Plattling", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="geo_latitude",
            field=models.CharField(blank=True, default="48.7785", max_length=20),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="geo_longitude",
            field=models.CharField(blank=True, default="12.8757", max_length=20),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="price_range",
            field=models.CharField(blank=True, default="Auf Anfrage", max_length=50),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="social_instagram",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="social_x",
            field=models.URLField(blank=True, default=""),
        ),
    ]
