# Generated by Django 5.2.13 on 2026-06-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_content", "0003_customer_logo_style_wide"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpressumBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ycms_impressumblock",
                "ordering": ["order", "id"],
            },
        ),
    ]
