# Generated by Django 5.2.13 on 2026-06-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_content", "0005_seed_impressum_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="impressumblock",
            name="content_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="impressumblock",
            name="content_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="impressumblock",
            name="title_de",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="impressumblock",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
