# Generated by Django 5.2.13 on 2026-06-07 12:34

from django.db import migrations, models


def backfill_privacy_policy_translations(apps, schema_editor):
    PrivacyPolicy = apps.get_model("cms_content", "PrivacyPolicy")
    for policy in PrivacyPolicy.objects.all():
        update_fields = []
        if policy.content_html and not policy.content_html_de:
            policy.content_html_de = policy.content_html
            update_fields.append("content_html_de")
        if policy.content_html and not policy.content_html_en:
            policy.content_html_en = policy.content_html
            update_fields.append("content_html_en")
        if policy.content_text and not policy.content_text_de:
            policy.content_text_de = policy.content_text
            update_fields.append("content_text_de")
        if policy.content_text and not policy.content_text_en:
            policy.content_text_en = policy.content_text
            update_fields.append("content_text_en")
        if update_fields:
            policy.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("cms_content", "0007_backfill_impressumblock_de"),
    ]

    operations = [
        migrations.AddField(
            model_name="privacypolicy",
            name="content_html_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="content_html_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="content_text_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="content_text_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.RunPython(backfill_privacy_policy_translations, migrations.RunPython.noop),
    ]
