# Generated by Django 5.2.13 on 2026-08-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_content", "0009_servicelocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="services_text_en",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="short_description_en",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="subtitle_en",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="testimonial_author_en",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="testimonial_en",
        ),
        migrations.RemoveField(
            model_name="impressumblock",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="impressumblock",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="content_html_en",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="content_text_en",
        ),
        migrations.RemoveField(
            model_name="textcontent",
            name="buttonText_en",
        ),
        migrations.RemoveField(
            model_name="textcontent",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="textcontent",
            name="header_en",
        ),
        migrations.RemoveField(
            model_name="textcontent",
            name="title_en",
        ),
    ]
