# Generated by Django 4.0.10 on 2026-03-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0058_remove_order_buyer_address_remove_orderitem_order_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='products', to='ycms.anyfile'),
        ),
    ]
