# Generated by Django 4.0.10 on 2026-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_price_when_showcase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='showcase_only',
            field=models.BooleanField(default=False),
        ),
    ]
